### ISSUE TITLE
Readme Levels are not working

### ISSUE THREAD

**Issue by mza7a** [ahkecha/Rainfall#1]
When you click on a level in your readme it takes you to the following :

```
https://github.com/ahkecha/Rainfall/blob/main/level00
```

But this link doesn't exist, and it should take you to this link instead :

```
https://github.com/ahkecha/Rainfall/blob/main/level0
```

Please fix this issue asap !

**Comment by ahkecha** [comment]
what an incredible and groundbreaking observation
